import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service – PalettAI",
  description: "Terms and conditions for using PalettAI.",
};

export default function TermsPage() {
  return (
    <div className="container max-w-3xl py-16">
      <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-10">Last updated: March 2026</p>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-foreground">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing or using PalettAI ("the Service"), you agree to be bound by these Terms of
            Service. If you do not agree, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            PalettAI is an AI-powered color palette generator. Free users receive up to 5 palette
            generations per day. Pro subscribers receive unlimited generations and additional features
            as described on the{" "}
            <a href="/pricing" className="text-primary underline hover:no-underline">pricing page</a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
          <p className="text-muted-foreground leading-relaxed">
            You are responsible for maintaining the confidentiality of your account credentials. You
            agree to notify us immediately of any unauthorized use of your account. We reserve the
            right to terminate accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. Subscriptions and Billing</h2>
          <p className="text-muted-foreground leading-relaxed">
            Pro subscriptions are billed monthly via Stripe. You may cancel at any time through the
            customer portal; your subscription remains active until the end of the current billing
            period. We do not offer refunds for partial months.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. Acceptable Use</h2>
          <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-muted-foreground">
            <li>Use the Service to generate harmful, offensive, or illegal content</li>
            <li>Attempt to circumvent rate limits or access controls</li>
            <li>Resell or sublicense access to the Service</li>
            <li>Use automated scripts to abuse the free generation tier</li>
            <li>Reverse engineer or scrape the Service</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            Color palettes generated by the Service are yours to use freely in personal and commercial
            projects. The PalettAI brand, logo, and codebase remain our intellectual property.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Disclaimer of Warranties</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service is provided "as is" without warranty of any kind. We do not guarantee that
            generated palettes will meet any specific accessibility or design standards. AI outputs
            may vary and are not guaranteed to be unique.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
          <p className="text-muted-foreground leading-relaxed">
            To the maximum extent permitted by law, PalettAI shall not be liable for any indirect,
            incidental, or consequential damages arising from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">9. Changes to Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update these terms from time to time. Continued use of the Service after changes
            constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">10. Governing Law</h2>
          <p className="text-muted-foreground leading-relaxed">
            These Terms are governed by the laws of New South Wales, Australia. Any disputes will be
            subject to the exclusive jurisdiction of the courts of New South Wales.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">11. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            For questions about these terms, contact us at{" "}
            <a href="mailto:legal@palettai.com" className="text-primary underline hover:no-underline">
              legal@palettai.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
